### PR TITLE
Sending long messages, issue #6.

### PR DESCRIPTION
**Pull request by alecpetrosky**

### CODE REVIEW

**Comment by lgg** [comment]
@KostyaEsmukov please, can you merge this?

**Comment by n3roGit** [comment]
Cool pull request please add this

**Comment by joshuapullin** [comment]
@KostyaEsmukov @alecpetrosky any chance this could get merged please?
This is a good enhancement which I have hit errors with recently.

**Comment by KostyaEsmukov** [comment]
I'm sorry but I won't be merging this.

Paginating at characters level is prone to breaking words and formatting.

If support for >4kb messages is desired, a smarter pagination should be implemented: which respects formatting and paragraphs. I'm not willing to implement or support this at the moment.

(Also this diff is quite clunky and contains irrelevant changes).

**Pull request closed without merging**
